import { ProjectProps } from "../types"

// Project Data
export const Project_Data: ProjectProps[] = [
  {
    id: 1,
    title: "Matrix",
    description: "",
    imgUrl: "/images/projects/8.png",
    tag: ["All","Web"],
    gitUrl: "",
    previewUrl: "https://matrix-hackbvp.vercel.app/",
    techStack: ["React", "Node.js", "Express", "MongoDB", "Tailwind CSS", "TypeScript"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Team",
    duration: "1 month",
  
  },
  {
    id: 2,
    title: "FileShare",
    description: "The project is a user-friendly file-sharing platform. It's built with React on the frontend and Node.js with Express on the backend. Users can easily upload files, keep track of downloads, and retrieve them using convenient links. It's all about hassle-free file sharing!",
    imgUrl: "/images/projects/7.png",
    tag: ["All","Web"],
    gitUrl: "",
    previewUrl: "",
    techStack: ["React", "Node.js", "Express", "MongoDB", "Tailwind CSS", "TypeScript"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "2 week",
  },
  {
    id: 3,
    title: "Bloggies",
    description: "lorem20",
    imgUrl: "/images/projects/6.png",
    tag: ["All"],
    gitUrl: "",
    previewUrl: "",
    techStack: ["React", "Node.js", "Express", "MongoDB"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 month",
    },
  {
    id: 8,
    title: "readLites",
    description: "readLites makes reading fun and easy! It uses smart technology to show pictures and pick out important ideas from stories. This helps you understand and enjoy books better!",
    imgUrl: "/images/projects/1.png",
    tag: ["All","ML"],
    gitUrl: "",
    previewUrl: "https://readlites-deepsolv.streamlit.app/",
    techStack: ["Python", "Streamlit", "Openai", "gtts"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Team",
    duration: "1 month",
  },
  {
    id: 7,
    title: "NexDrive",
    description: "NexDrive is a dynamic car marketplace built with Next.js, Tailwind CSS, and TypeScript. Integrated with Rapid API for enhanced features and a user-friendly experience.",
    imgUrl: "/images/projects/2.png",
    tag: ["All","Web"],
    gitUrl: "",
    previewUrl: "https://nexdrive-085.vercel.app",
    techStack: ["Next.js", "Tailwind CSS", "TypeScript", "Rapid API"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "2 weeks",
  },
  {
    id: 6,
    title: "PromptHub",
    description: "\"PromptHub\" is a web platform designed for sharing prompts. It provides a space for users to post and explore various prompts that can be used for creative writing, brainstorming, or any context that requires a starting point.",
    imgUrl: "/images/projects/3.png",
    tag: ["All","Web"],
    gitUrl: "",
    previewUrl: "https://prompthub-085.vercel.app",
    techStack: ["Nextjs", "MongoDB", "Tailwind CSS", "TypeScript", "Authjs"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 month",
  },
  {
    id: 5,
    title: "SmartReadme",
    description: "SmartReadME is a README file generator powered by LangchainJS. It helps developers to quickly generate a quality README.md file in Markdown format for their projects.",
    imgUrl: "/images/projects/4.png",
    tag: ["All","ML"],
    gitUrl: "",
    previewUrl: "https://smartreadme.streamlit.app/",
    techStack: ["Python", "Streamlit", "Openai"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 month"
  },
  {
    id: 4,
    title: "CodexSphere",
    description: "CodexSphere is a web platform uniting book lovers. Built with React JS, MongoDB, and Tailwind CSS, it allows seamless management of personal book collections. Add, explore, and dive into a world of literature with CodexSphere - where your bookshelf transforms into a gateway to endless literary journeys",
    imgUrl: "/images/projects/5.png",
    tag: ["All","Web"],
    gitUrl: "",
    previewUrl: "",
    techStack: ["React", "Node.js", "Express", "MongoDB", "Tailwind CSS", "TypeScript"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 month",
  },
]

export const navLinks = [
    {
      title: "About",
      path: "#abouts",
    },
    {
      title: "Projects",
      path: '#projects',
    },
    {
      title: 'Contact',
      path: '#contact'
    }
  ]