import { ProjectProps } from "../types"

// Project Data
export const Project_Data: ProjectProps[] = [
  {
    id: 1,
    title: "Bookies",
    description: "Bookies is a web platform designed for sharing books. It provides a space for users to post and explore various books that can be used for reading, brainstorming, or any context that requires a starting point.",
    imgUrl: "/images/projects/11.png",
    tag: ["All","ML"],
    gitUrl: "",
    previewUrl: "",
    techStack: ["React", "Node.js", "Express", "MongoDB", "Tailwind CSS", "TypeScript", "Authjs", "Openai", "gtts"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Team",
    duration: "1 month",
  },
  {
    id: 2,
    title: "Matrix",
    description: "Experience a new era in metro travel with Matrix. Seamlessly enter using your smartphone, enjoy precise fare calculation, and receive real-time updates. This project is a testament to my participation and innovation at Hack-BVP@5.0. Elevate your urban commute with Matrix.",
    imgUrl: "/images/projects/8.png",
    tag: ["All","Web"],
    gitUrl: "",
    previewUrl: "https://matrix-hackbvp.vercel.app/",
    techStack: ["React", "Node.js", "Express", "MongoDB", "Tailwind CSS", "TypeScript"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Team",
    duration: "1 month",
  
  },
  {
    id: 3,
    title: "FileShare",
    description: "The project is a user-friendly file-sharing platform. It's built with React on the frontend and Node.js with Express on the backend. Users can easily upload files, keep track of downloads, and retrieve them using convenient links. It's all about hassle-free file sharing!",
    imgUrl: "/images/projects/7.png",
    tag: ["All","Web"],
    gitUrl: "",
    previewUrl: "",
    techStack: ["React", "Node.js", "Express", "MongoDB", "Tailwind CSS", "TypeScript"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "2 week",
  },
  {
    id: 4,
    title: "Bloggies",
    description: "A Blogging platform built with React JS, MongoDB, and Tailwind CSS. It allows users to create, read, update, and delete blog posts. Users can also like and comment on posts.",
    imgUrl: "/images/projects/6.png",
    tag: ["All"],
    gitUrl: "",
    previewUrl: "",
    techStack: ["React", "Node.js", "Express", "MongoDB"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 month",
  },
  {
    id: 5,
    title: "CodexSphere",
    description: "CodexSphere is a web platform uniting book lovers. Built with React JS, MongoDB, and Tailwind CSS, it allows seamless management of personal book collections. Add, explore, and dive into a world of literature with CodexSphere - where your bookshelf transforms into a gateway to endless literary journeys",
    imgUrl: "/images/projects/5.png",
    tag: ["All","Web"],
    gitUrl: "",
    previewUrl: "",
    techStack: ["React", "Node.js", "Express", "MongoDB"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 month",
  },
  {
    id: 6,
    title: "SmartReadme",
    description: "SmartReadME is a README file generator powered by LangchainJS. It helps developers to quickly generate a quality README.md file in Markdown format for their projects.",
    imgUrl: "/images/projects/4.png",
    tag: ["All","ML"],
    gitUrl: "",
    previewUrl: "https://smartreadme.streamlit.app/",
    techStack: ["Python", "Streamlit", "Openai"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 month"
  },
  {
    id: 7,
    title: "PromptHub",
    description: "\"PromptHub\" is a web platform designed for sharing prompts. It provides a space for users to post and explore various prompts that can be used for creative writing, brainstorming, or any context that requires a starting point.",
    imgUrl: "/images/projects/3.png",
    tag: ["All","Web"],
    gitUrl: "",
    previewUrl: "https://prompthub-085.vercel.app",
    techStack: ["Nextjs", "MongoDB", "Tailwind CSS", "TypeScript", "Authjs"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 month",
  },
  {
    id: 8,
    title: "NexDrive",
    description: "NexDrive is a dynamic car marketplace built with Next.js, Tailwind CSS, and TypeScript. Integrated with Rapid API for enhanced features and a user-friendly experience.",
    imgUrl: "/images/projects/2.png",
    tag: ["All","Web"],
    gitUrl: "",
    previewUrl: "https://nexdrive-085.vercel.app",
    techStack: ["Next.js", "Tailwind CSS", "TypeScript", "Rapid API"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "2 weeks",
  },
  {
    id: 9,
    title: "readLites",
    description: "readLites makes reading fun and easy! It uses smart technology to show pictures and pick out important ideas from stories. This helps you understand and enjoy books better!",
    imgUrl: "/images/projects/1.png",
    tag: ["All","ML"],
    gitUrl: "",
    previewUrl: "https://readlites-deepsolv.streamlit.app/",
    techStack: ["Python", "Streamlit", "Openai", "gtts"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Team",
    duration: "1 month",
  },
  {
    id: 10,
    title: "GojoTalk",
    description: "GojoTalk: Experience 'Yōkoso'—Satoru Gojo's welcome in every interaction. Where intelligent conversations seamlessly blend with the essence of Japanese charisma, making each chat a dynamic and inviting experience.",
    imgUrl: "/images/projects/9.png",
    tag: ["All","Web", "ML"],
    gitUrl: "",
    previewUrl: "https://gojotalk.vercel.app/",
    techStack: ["React", "Node.js", "Express", "Tailwind CSS"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 week",
  },
  {
    id: 11,
    title: "PaLM ChatBot",
    description: "GojoTalk is an interactive chat platform centered around the character Satoru Gojo from the anime and manga series \"Jujutsu Kaisen\". Users engage in dynamic conversations with a virtual representation of Gojo, exploring various facets of his personality, experiences, and expertise in Jujutsu sorcery.",
    imgUrl: "/images/projects/10.png",
    tag: ["All","ML"],
    gitUrl: "https://github.com/Priyanshu085/PaLM_API_Repo/blob/my/GojoTalk.ipynb",
    previewUrl: "",
    techStack: ["Python", "PaLM API", "ChatBot"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 week",
  },
  {
    id: 12,
    title: "EE_DeepLearning",
    description: "This repository contains code and notes related to my learning journey in deep learning. I use it to track my progress, store code snippets, and document key concepts in Notion.",
    imgUrl: "/images/projects/12.png",
    tag: ["All","ML"],
    gitUrl: "https://github.com/Priyanshu085/EE_DeepLearning",
    previewUrl: "https://priyanshu085.github.io/EE_DeepLearning/",
    techStack: ["Python", "Tensorflow", "Keras", "Pytorch"],
    challengesFaced: ["Finding the worthy playlist", "Finding the right communities to explore DL"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "50 Days",
  }
]

export const navLinks = [
    {
      title: "About",
      path: "#abouts",
    },
    {
      title: "Projects",
      path: '#projects',
    },
    {
      title: 'Contact',
      path: '#contact'
    }
  ]
  
export const socialLinks = [
    {
      name: "Github",
      url: "https://gitub.com/Priyanshu085",
      icon: "github",
    },
    {
      name: "LinkedIn",
      url: "https://www.linkedin.com/in/priyanshu085/",
      icon: "linkedin",
    },
    {
      name: "Twitter",
      url: "https://twitter.com/Priyanshu0x85",
      icon: "twitter",
    },
    {
      name: "Instagram",
      url: "https://www.instagram.com/priyanshu085/",
      icon: "instagram",
    },
    {
      name: "Mail",
      url: "mailto:qbpriyanshu007@gmail.com",
      icon: "mail",
    },
    {
      name: "CodeChef",
      url: "",
      icon: "codechef",
    },
    {
      
    }
  ]
