import { ProjectProps, ProjectTagProps } from "@/types";

export const project: ProjectTagProps[] = [
  {
    tag: "All",
    name: "All Projects",
  },
  {
    tag: "Web",
    name: "Web Dev.",
  },
  {
    tag: "ML",
    name: "Machine Learning",
  },
];
// Project Data
export const Project_Data: ProjectProps[] = [
  {
    id: 5,
    title: "CodexSphere",
    description:
      "CodexSphere is a web platform uniting book lovers. Built with React JS, MongoDB, and Tailwind CSS, it allows seamless management of personal book collections. Add, explore, and dive into a world of literature with CodexSphere - where your bookshelf transforms into a gateway to endless literary journeys",
    imgUrl: "/images/projects/5.png",
    tag: ["All", "Web"],
    gitUrl: "",
    previewUrl: "",
    techStack: ["React", "Node.js", "Express", "MongoDB"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 month",
  },
  {
    id: 6,
    title: "SmartReadme",
    description:
      "SmartReadME is a README file generator powered by LangchainJS. It helps developers to quickly generate a quality README.md file in Markdown format for their projects.",
    imgUrl: "/images/projects/4.png",
    tag: ["All", "ML"],
    gitUrl: "",
    previewUrl: "https://smartreadme.streamlit.app/",
    techStack: ["Python", "Streamlit", "Openai"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 month",
  },
  {
    id: 8,
    title: "NexDrive",
    description:
      "NexDrive is a dynamic car marketplace built with Next.js, Tailwind CSS, and TypeScript. Integrated with Rapid API for enhanced features and a user-friendly experience.",
    imgUrl: "/images/projects/2.png",
    tag: ["All", "Web"],
    gitUrl: "",
    previewUrl: "https://nexdrive-085.vercel.app",
    techStack: ["Next.js", "Tailwind CSS", "TypeScript", "Rapid API"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "2 weeks",
  },
  {
    id: 9,
    title: "readLites",
    description:
      "readLites makes reading fun and easy! It uses smart technology to show pictures and pick out important ideas from stories. This helps you understand and enjoy books better!",
    imgUrl: "/images/projects/1.png",
    tag: ["All", "ML"],
    gitUrl: "",
    previewUrl: "https://readlites-deepsolv.streamlit.app/",
    techStack: ["Python", "Streamlit", "Openai", "gtts"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Team",
    duration: "1 month",
  },
  {
    id: 13,
    title: "GojoTalk",
    description:
      "GojoTalk: Experience 'Yōkoso'—Satoru Gojo's welcome in every interaction. Where intelligent conversations seamlessly blend with the essence of Japanese charisma, making each chat a dynamic and inviting experience.",
    imgUrl: "/images/projects/9.png",
    tag: ["All", "Web", "ML"],
    gitUrl: "",
    previewUrl: "https://gojotalk.vercel.app/",
    techStack: ["React", "Node.js", "Express", "Gemini AI", "Tailwind CSS"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 week",
  },
  {
    id: 11,
    title: "PaLM ChatBot",
    description:
      'GojoTalk is an interactive chat platform centered around the character Satoru Gojo from the anime and manga series "Jujutsu Kaisen". Users engage in dynamic conversations with a virtual representation of Gojo, exploring various facets of his personality, experiences, and expertise in Jujutsu sorcery.',
    imgUrl: "/images/projects/10.png",
    tag: ["All", "ML"],
    gitUrl: "https://github.com/coderx85/PaLM_API_Repo/blob/my/GojoTalk.ipynb",
    previewUrl: "",
    techStack: ["Python", "Gemini AI", "ChatBot"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 week",
  },
  {
    id: 12,
    title: "LeviLayer",
    description:
      "This project provides an interactive dashboard for analyzing the different activation function in neural networks. LeviLayer is a novel activation function that has shown promising results in various deep learning tasks. With this dashboard, users can explore the behavior of LeviLayer and compare it with other popular activation functions.",
    imgUrl: "",
    tag: ["All", "ML"],
    gitUrl: "https://github.com/coderx85/LeviLayer.git",
    previewUrl: "",
    techStack: ["Python", "TensorFlow"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 week",
  },
  {
    id: 14,
    title: "StyleBlend",
    description:
      "StyleBlend is a project for artistic style transfer using the VGG19 convolutional neural network architecture. It allows users to blend the content of one image with the style of another image, creating visually appealing compositions.",
    imgUrl: "",
    tag: ["All", "ML"],
    gitUrl: "https://github.com/coderx85/StyleBlend.git",
    previewUrl: "",
    techStack: ["Python", "TensorFlow", "Keras"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 week",
  },
  {
    id: 7,
    title: "Plant disease prediction",
    description: "",
    imgUrl: "",
    tag: ["All", "ML"],
    gitUrl: "https://github/coderx85/Plant-disease-prediction.git",
    previewUrl: "",
    techStack: ["Python", "TensorFlow", "Keras"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 week",
  },
  {
    id: 15,
    title: "PromptHub",
    description:
      '"PromptHub" is a web platform designed for sharing prompts. It provides a space for users to post and explore various prompts that can be used for creative writing, brainstorming, or any context that requires a starting point.',
    imgUrl: "/images/projects/3.png",
    tag: ["All", "Web"],
    gitUrl: "",
    previewUrl: "https://prompthub-085.vercel.app",
    techStack: ["Nextjs", "MongoDB", "Tailwind CSS", "TypeScript", "Authjs"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 month",
  },
  {
    id: 17,
    title: "Mitra-Bot",
    description:
      " Welcome to Mitra Bot [Machine Interactive Tutor for Responsive Answers By Optimizing Technology] - your friendly AI-powered tutor 📚.",
    imgUrl: "/images/projects/17.png",
    tag: ["All", "ML"],
    gitUrl: "https://github.com/coderx85/Mitra-Bot.git",
    previewUrl: "",
    techStack: ["Python", "groq", "llama-3-base"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 week",
  },
  {
    id: 18,
    title: "Stake",
    description:
      "Stake Game Simulation is a project that simulates a game involving stakes and outcomes based on random patterns. The project includes frontend and backend components to create a visual representation of the game simulation.",
    imgUrl: "/images/projects/18.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/coderx85/stake.git",
    previewUrl: "https://stake-vert.vercel.app/",
    techStack: [
      "React",
      "Node.js",
      "Express",
      "MongoDB",
      "Tailwind CSS",
      "TypeScript",
      "Authjs",
      "Openai",
      "gtts",
    ],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "1 month",
  },
  {
    id: 19,
    title: "Bux",
    description:
      "A storage management system. It is designed to help manage and organize storage units efficiently.",
    imgUrl: "/images/projects/19.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/coderx85/bux.git",
    previewUrl: "https://bux-storage.vercel.app/",
    techStack: ["Next.js", "Appwrite", "Shadcn", "Clerk.js"],
    challengesFaced: [],
    lessonsLearned: [],
    contributionType: "Solo",
    duration: "2 weeks",
  },
  {
    id: 20,
    title: "Fiverplus",
    description: "",
    imgUrl: "",
    tag: ["All", "Web"],
    gitUrl: "fiverplus",
    previewUrl: "",
    techStack: ["Next.js", "Appwrite", "Shadcn", "Clerk.js", "convex"],
    challengesFaced: [],
    lessonsLearned: [],
    contributionType: "Solo",
    duration: "3 weeks",
  },
  {
    id: 21,
    title: "SensAI",
    description:
      "SensAI is a web application designed to help users generate cover letters, manage their profiles, and prepare for interviews. The application leverages various modern web technologies and libraries to provide a seamless user experience.",
    imgUrl: "/images/projects/21.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/Coderx85sensai.git",
    previewUrl: "https://sensai-eta.vercel.app/",
    techStack: ["Next.js", "Appwrite", "Shadcn", "Clerk.js", "Gemini AI"],
    challengesFaced: [],
    lessonsLearned: [],
    contributionType: "Solo",
    duration: "1 weeks",
  },
  {
    id: 22,
    title: "DevnTalk",
    description:
      "DevnTalk is a developer-centric collaboration platform that integrates real-time communication, live streaming, and structured meetings. It allows users to create or join workspaces, invite members. Designed for remote teams. DevnTalk enhances productivity by providing a seamless environment for discussions, and project tracking.",
    imgUrl: "/images/projects/22.png",
    tag: ["All", "Web"],
    gitUrl: "https://github.com/coderx85/DevTalk.git",
    previewUrl: "https://devntalk.vercel.app/",
    techStack: ["Next.js", "Tailwind CSS", "Clerksjs", "Shadcn"],
    challengesFaced: ["Challenge 1", "Challenge 2"],
    lessonsLearned: ["Lesson 1", "Lesson 2"],
    contributionType: "Solo",
    duration: "2 months",
  },
];
